// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: proto/demo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetingRequest) Reset() {
	*x = GreetingRequest{}
	mi := &file_proto_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingRequest) ProtoMessage() {}

func (x *GreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingRequest.ProtoReflect.Descriptor instead.
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{0}
}

func (x *GreetingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GreetingMessage string                 `protobuf:"bytes,1,opt,name=greeting_message,json=greetingMessage,proto3" json:"greeting_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GreetingResponse) Reset() {
	*x = GreetingResponse{}
	mi := &file_proto_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingResponse) ProtoMessage() {}

func (x *GreetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingResponse.ProtoReflect.Descriptor instead.
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{1}
}

func (x *GreetingResponse) GetGreetingMessage() string {
	if x != nil {
		return x.GreetingMessage
	}
	return ""
}

// Streaming
// The server is streaming to the client
type CountdownRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartingNumber int32                  `protobuf:"varint,1,opt,name=starting_number,json=startingNumber,proto3" json:"starting_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CountdownRequest) Reset() {
	*x = CountdownRequest{}
	mi := &file_proto_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownRequest) ProtoMessage() {}

func (x *CountdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownRequest.ProtoReflect.Descriptor instead.
func (*CountdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{2}
}

func (x *CountdownRequest) GetStartingNumber() int32 {
	if x != nil {
		return x.StartingNumber
	}
	return 0
}

type CountdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentNumber int32                  `protobuf:"varint,1,opt,name=current_number,json=currentNumber,proto3" json:"current_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountdownResponse) Reset() {
	*x = CountdownResponse{}
	mi := &file_proto_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownResponse) ProtoMessage() {}

func (x *CountdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownResponse.ProtoReflect.Descriptor instead.
func (*CountdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{3}
}

func (x *CountdownResponse) GetCurrentNumber() int32 {
	if x != nil {
		return x.CurrentNumber
	}
	return 0
}

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_proto_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{4}
}

func (x *SumRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type SumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int32                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	mi := &file_proto_demo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{5}
}

func (x *SumResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type ChatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncomingMessage string                 `protobuf:"bytes,1,opt,name=incoming_message,json=incomingMessage,proto3" json:"incoming_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_demo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{6}
}

func (x *ChatRequest) GetIncomingMessage() string {
	if x != nil {
		return x.IncomingMessage
	}
	return ""
}

type ChatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OutgoingMessage string                 `protobuf:"bytes,1,opt,name=outgoing_message,json=outgoingMessage,proto3" json:"outgoing_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_demo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_demo_proto_rawDescGZIP(), []int{7}
}

func (x *ChatResponse) GetOutgoingMessage() string {
	if x != nil {
		return x.OutgoingMessage
	}
	return ""
}

var File_proto_demo_proto protoreflect.FileDescriptor

const file_proto_demo_proto_rawDesc = "" +
	"\n" +
	"\x10proto/demo.proto\x12\x04demo\"%\n" +
	"\x0fGreetingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"=\n" +
	"\x10GreetingResponse\x12)\n" +
	"\x10greeting_message\x18\x01 \x01(\tR\x0fgreetingMessage\";\n" +
	"\x10CountdownRequest\x12'\n" +
	"\x0fstarting_number\x18\x01 \x01(\x05R\x0estartingNumber\":\n" +
	"\x11CountdownResponse\x12%\n" +
	"\x0ecurrent_number\x18\x01 \x01(\x05R\rcurrentNumber\"$\n" +
	"\n" +
	"SumRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\"\x1f\n" +
	"\vSumResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x05R\x03sum\"8\n" +
	"\vChatRequest\x12)\n" +
	"\x10incoming_message\x18\x01 \x01(\tR\x0fincomingMessage\"9\n" +
	"\fChatResponse\x12)\n" +
	"\x10outgoing_message\x18\x01 \x01(\tR\x0foutgoingMessage2M\n" +
	"\x0fGreetingService\x12:\n" +
	"\tGreetUser\x12\x15.demo.GreetingRequest\x1a\x16.demo.GreetingResponse2X\n" +
	"\x10CountdownService\x12D\n" +
	"\x0fCountdownNumber\x12\x16.demo.CountdownRequest\x1a\x17.demo.CountdownResponse0\x012:\n" +
	"\n" +
	"SumService\x12,\n" +
	"\x03Sum\x12\x10.demo.SumRequest\x1a\x11.demo.SumResponse(\x012@\n" +
	"\vChatService\x121\n" +
	"\x04Chat\x12\x11.demo.ChatRequest\x1a\x12.demo.ChatResponse(\x010\x01B)Z'github.com/Infinity8080/grpc-demo/protob\x06proto3"

var (
	file_proto_demo_proto_rawDescOnce sync.Once
	file_proto_demo_proto_rawDescData []byte
)

func file_proto_demo_proto_rawDescGZIP() []byte {
	file_proto_demo_proto_rawDescOnce.Do(func() {
		file_proto_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_demo_proto_rawDesc), len(file_proto_demo_proto_rawDesc)))
	})
	return file_proto_demo_proto_rawDescData
}

var file_proto_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_demo_proto_goTypes = []any{
	(*GreetingRequest)(nil),   // 0: demo.GreetingRequest
	(*GreetingResponse)(nil),  // 1: demo.GreetingResponse
	(*CountdownRequest)(nil),  // 2: demo.CountdownRequest
	(*CountdownResponse)(nil), // 3: demo.CountdownResponse
	(*SumRequest)(nil),        // 4: demo.SumRequest
	(*SumResponse)(nil),       // 5: demo.SumResponse
	(*ChatRequest)(nil),       // 6: demo.ChatRequest
	(*ChatResponse)(nil),      // 7: demo.ChatResponse
}
var file_proto_demo_proto_depIdxs = []int32{
	0, // 0: demo.GreetingService.GreetUser:input_type -> demo.GreetingRequest
	2, // 1: demo.CountdownService.CountdownNumber:input_type -> demo.CountdownRequest
	4, // 2: demo.SumService.Sum:input_type -> demo.SumRequest
	6, // 3: demo.ChatService.Chat:input_type -> demo.ChatRequest
	1, // 4: demo.GreetingService.GreetUser:output_type -> demo.GreetingResponse
	3, // 5: demo.CountdownService.CountdownNumber:output_type -> demo.CountdownResponse
	5, // 6: demo.SumService.Sum:output_type -> demo.SumResponse
	7, // 7: demo.ChatService.Chat:output_type -> demo.ChatResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_demo_proto_init() }
func file_proto_demo_proto_init() {
	if File_proto_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_demo_proto_rawDesc), len(file_proto_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_demo_proto_goTypes,
		DependencyIndexes: file_proto_demo_proto_depIdxs,
		MessageInfos:      file_proto_demo_proto_msgTypes,
	}.Build()
	File_proto_demo_proto = out.File
	file_proto_demo_proto_goTypes = nil
	file_proto_demo_proto_depIdxs = nil
}
